### ISSUE TITLE
Suggestion: Use the EFF Word List

### ISSUE THREAD

**Issue by rjosborne** [rafaelcpalmeida/ChromeDicewarePasswordsGenerator#2]
The EFF list seems to result in passwords that are much easier to remember, without affecting the security of the password in any way (technically it can make it more secure if you don't use a separator as I don't believe the EFF list contains cases such as IN and PUT which combine to make INPUT which is also on the list).

I've created a fork that uses the EFF list for my own use - I'd be more than happy to create a pull request if desired.

It might even be worth looking at trying to combine the two and letting people choose the list to generate passwords from seen as the average length of words in the EFF list is longer than in the original diceware list.

**Comment by rafaelcpalmeida** [comment]
Hey @rjosborne, thank you for your feedback.

Your PR would be welcome! I can also create a new version to allow users to choose between the original list and EFF 👍
